### ISSUE TITLE
NoMethodError: undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by CloCkWeRX** [mhfs/sidekiq-failures#110]
```
Error message
NoMethodError: undefined method `size' for nil:NilClass

```

```
…q-failures-0.4.5/lib/sidekiq/failures/
web_extension.rb:  72:in `block (2 levels) in singleton class'
…q-failures-0.4.5/lib/sidekiq/failures/
web_extension.rb:  55:in `each'
…q-failures-0.4.5/lib/sidekiq/failures/
web_extension.rb:  55:in `block in singleton class'
…q-failures-0.4.5/lib/sidekiq/failures/
web_extension.rb:  19:in `instance_eval'
…q-failures-0.4.5/lib/sidekiq/failures/
web_extension.rb:  19:in `singleton class'
…q-failures-0.4.5/lib/sidekiq/failures/
web_extension.rb:  17:in `__tilt_70120676869040'
…bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/
template.rb: 170:in `call'
…bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/
template.rb: 170:in `evaluate'
…bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/
template.rb: 103:in `render'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 823:in `render'
…q-failures-0.4.5/lib/sidekiq/failures/
web_extension.rb:  25:in `block in registered'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1611:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1611:in `block in compile!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 975:in `[]'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 975:in `block (3 levels) in route!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 994:in `route_eval'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 975:in `block (2 levels) in route!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1015:in `block in process_route'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1013:in `catch'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1013:in `process_route'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 973:in `block in route!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 972:in `each'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 972:in `route!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1085:in `block in dispatch!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `block in invoke'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `catch'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `invoke'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1082:in `dispatch!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 907:in `block in call!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `block in invoke'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `catch'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1067:in `invoke'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 907:in `call!'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 895:in `call'
…ack-protection-1.5.3/lib/rack/protection/
xss_header.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…protection-1.5.3/lib/rack/protection/
path_traversal.rb:  16:in `call'
…rack-protection-1.5.3/lib/rack/protection/
json_csrf.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…-protection-1.5.3/lib/rack/protection/
frame_options.rb:  31:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…ack-protection-1.5.3/lib/rack/protection/
xss_header.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…protection-1.5.3/lib/rack/protection/
path_traversal.rb:  16:in `call'
…rack-protection-1.5.3/lib/rack/protection/
json_csrf.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/
base.rb:  49:in `call'
…-protection-1.5.3/lib/rack/protection/
frame_options.rb:  31:in `call'
…/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/
id.rb: 225:in `context'
…/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/
id.rb: 220:in `call'
…ndle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/
nulllogger.rb:   9:in `call'
…10/.bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/
head.rb:  11:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb: 182:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:2013:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1487:in `block in call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1787:in `synchronize'
…ndle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/
base.rb:1487:in `call'
…ctionpack-4.1.15/lib/action_dispatch/routing/
mapper.rb:  45:in `call'
…ctionpack-4.1.15/lib/action_dispatch/journey/
router.rb:  73:in `block in call'
…ctionpack-4.1.15/lib/action_dispatch/journey/
router.rb:  59:in `each'
…ctionpack-4.1.15/lib/action_dispatch/journey/
router.rb:  59:in `call'
…onpack-4.1.15/lib/action_dispatch/routing/
route_set.rb: 690:in `call'
…uby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/
strategy.rb: 186:in `call!'
…uby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/
strategy.rb: 164:in `call'
…ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/
builder.rb:  59:in `call'
…10/.bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/
etag.rb:  23:in `call'
…/ruby/2.2.0/gems/rack-1.5.5/lib/rack/
conditionalget.rb:  25:in `call'
…10/.bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/
head.rb:  11:in `call'
…4.1.15/lib/action_dispatch/middleware/
params_parser.rb:  27:in `call'
…ionpack-4.1.15/lib/action_dispatch/middleware/
flash.rb: 254:in `call'
…/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/
id.rb: 225:in `context'
…/2.2.0/gems/rack-1.5.5/lib/rack/session/abstract/
id.rb: 220:in `call'
…npack-4.1.15/lib/action_dispatch/middleware/
cookies.rb: 562:in `call'
…ruby/2.2.0/gems/safe_cookies-0.2.1/lib/
safe_cookies.rb:  43:in `call'
…ack-4.1.15/lib/action_dispatch/middleware/
callbacks.rb:  29:in `block in call'
…s/activesupport-4.1.15/lib/active_support/
callbacks.rb:  82:in `run_callbacks'
…ack-4.1.15/lib/action_dispatch/middleware/
callbacks.rb:  27:in `call'
…ack-4.1.15/lib/action_dispatch/middleware/
remote_ip.rb:  76:in `call'
….15/lib/action_dispatch/middleware/
debug_exceptions.rb:  17:in `call'
…1.15/lib/action_dispatch/middleware/
show_exceptions.rb:  30:in `call'
…by/2.2.0/gems/railties-4.1.15/lib/rails/rack/
logger.rb:  38:in `call_app'
…by/2.2.0/gems/railties-4.1.15/lib/rails/rack/
logger.rb:  20:in `block in call'
…ivesupport-4.1.15/lib/active_support/
tagged_logging.rb:  68:in `block in tagged'
…ivesupport-4.1.15/lib/active_support/
tagged_logging.rb:  26:in `tagged'
…ivesupport-4.1.15/lib/active_support/
tagged_logging.rb:  68:in `tagged'
…by/2.2.0/gems/railties-4.1.15/lib/rails/rack/
logger.rb:  20:in `call'
…/ruby/2.2.0/gems/silencer-0.6.0/lib/silencer/
logger.rb:  17:in `call'
…ck-4.1.15/lib/action_dispatch/middleware/
request_id.rb:  21:in `call'
…/ruby/2.2.0/gems/rack-1.5.5/lib/rack/
methodoverride.rb:  21:in `call'
….bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/
runtime.rb:  17:in `call'
…ctive_support/cache/strategy/
local_cache_middleware.rb:  26:in `call'
…bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/
sendfile.rb: 112:in `call'
…le/ruby/2.2.0/gems/railties-4.1.15/lib/rails/
engine.rb: 514:in `call'
…by/2.2.0/gems/railties-4.1.15/lib/rails/
application.rb: 144:in `call'
…e/ruby/2.2.0/gems/railties-4.1.15/lib/rails/
railtie.rb: 194:in `public_send'
…e/ruby/2.2.0/gems/railties-4.1.15/lib/rails/
railtie.rb: 194:in `method_missing'
…lib/phusion_passenger/rack/
thread_handler_extension.rb:  74:in `process_request'
…ib/phusion_passenger/request_handler/
thread_handler.rb: 141:in `accept_and_process_next_request'
…ib/phusion_passenger/request_handler/
thread_handler.rb: 109:in `main_loop'
…senger-4.0.60/lib/phusion_passenger/
request_handler.rb: 455:in `block (3 levels) in start_threads'
```

```
    sidekiq (4.1.4)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      redis (~> 3.2, >= 3.2.1)
      sinatra (>= 1.4.7)
    sidekiq-failures (0.4.5)
      sidekiq (>= 2.16.0)
```

**Comment by CloCkWeRX** [comment]
:/ I can't tell if
```
FailureSet.new.clear
```
boils down to JobSet.new.clear or SortedSet.new.clear (though Jobset < Sortedset)

SortedSet appears to define it:
```
    def size
      Sidekiq.redis { |c| c.zcard(name) }
    end
```
and
```
    def clear
      Sidekiq.redis do |conn|
        conn.del(name)
      end
    end
    alias_method :💣, :clear
```
and I get a bit lost trying to work out what exactly Sidekiq.redis is beyond a connection, and if it provides a .del method which invokes .size somehow.

**Comment by mcasper** [comment]
Resolved by https://github.com/mhfs/sidekiq-failures/pull/122
