### ISSUE TITLE
TypeError: no implicit conversion of Integer into String

### ISSUE THREAD

**Issue by John-Nenniger** [mhfs/sidekiq-failures#120]
https://github.com/mhfs/sidekiq-failures/blob/ade3c0035e8b7df0821a71328fe31dc706226aeb/lib/sidekiq/failures/middleware.rb#L32

I'm getting this error whenever my worker fails while trying to hit an external api.  It's not a huge deal because the worker would fail anyway, but it's not a very helpful error message.

**Comment by John-Nenniger** [comment]
Here's the stack trace:
```
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-failures-1.0.0/lib/sidekiq/failures/middleware.rb:32:in `+'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-failures-1.0.0/lib/sidekiq/failures/middleware.rb:32:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq.rb:95:in `block in redis'
/app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq.rb:92:in `redis'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-failures-1.0.0/lib/sidekiq/failures/middleware.rb:29:in `rescue in call'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-failures-1.0.0/lib/sidekiq/failures/middleware.rb:7:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:166:in `block in process'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/job_retry.rb:98:in `local'

```
